name: TUF-on-CI repository tests

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '17 4,10,16,22 * * *'

permissions: {}

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Smoke test TUF-on-CI repository with a TUF client
        uses: theupdateframework/tuf-on-ci/actions/test-repository@ebf63d46b20e8c019e7752f8fb57c28931f96cfc # v0.9.0
        with:
          metadata_url: https://sigstore.github.io/root-signing-staging/

  custom-smoke-test:
    permissions:
      id-token: 'write' # For signing with the GitHub workflow identity
    uses: ./.github/workflows/custom-test.yml
    with:
      metadata_url: https://sigstore.github.io/root-signing-staging/

  update-issue:
    runs-on: ubuntu-latest
    needs: [smoke-test, custom-smoke-test]
    # During workflow_call, caller updates issue
    if: always() && !cancelled() && github.workflow == 'TUF-on-CI repository tests'
    permissions:
      issues: 'write' # for modifying Issues
    steps:
      - name: Update the issue for the workflow
        uses: theupdateframework/tuf-on-ci/actions/update-issue@ebf63d46b20e8c019e7752f8fb57c28931f96cfc # v0.9.0
        with:
          token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
          success: ${{ !contains(needs.*.result, 'failure') }}
